% Produced by CVXGEN, 2020-11-11 20:11:32 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
G = params.G;
b = params.b;
idMat1 = params.idMat1;
idMat2 = params.idMat2;
lambda1 = params.lambda1;
lambda2 = params.lambda2;
lambda3 = params.lambda3;
n = params.n;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable sig(16, 1);

  minimize(lambda1*quad_form(idMat1*(b - G*n*sig), eye(3)) + lambda2*quad_form(idMat2*(b - G*n*sig), eye(3)) + lambda3*quad_form(n*sig, eye(12)));
  subject to
    0 <= sig;
cvx_end
vars.sig = sig;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
